resourcePackages:
- com.ors.junk.monty.rest.resource
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '0.0.1'
    title: Monty API
    description: 'This applications to consume Monty services'
    contact:
      email: masoud@fyaat.com
  servers:
   - url: /monty/api/
